### ISSUE TITLE
[Bug] Chat Brakes, No known reason yet.

### ISSUE THREAD

**Issue by TagCraftMC** [geNAZt/CloudChat#75]
We just got the whole "chat is broke mkay" issue again.
We have not fired the reload command and are running the following versions.
CC: 6.1.1
CCB: 2.0.1
YAMLER Bukkit: 2.0.0
YAMLER Bungee: 1.5.2 
BungeeLib: 1.6.1
Report: http://pastebin.com/3D7EV3q3
I could find no errors in the bungee's log or servers log in regards to the error, sorry.

**Comment by geNAZt** [comment]
Well the report does not tell me that something broke. Can you post some more Informations about your network setup ? Amount of Bungees, amount of Bukkits and the Channel YML would be nice

**Comment by TagCraftMC** [comment]
Sorry for the late reply, we just had it happen again.

We are up to date on all the versions. 
CC: 8.1.1
CCB: 3.1.2
YAMLER Bukkit: 2.2.1
YAMLER Bungee: 2.2.1
BungeeLib:  BungeeLib-2.0.0-20140319.222234-3-BungeeLib

We have one bungee and currently 6 servers.

Current config: http://pastebin.com/SdPjtQwT
Example of a server channel: http://pastebin.com/FSninCJF
Example of Perms: http://pastebin.com/upuN2WXT

**Comment by TagCraftMC** [comment]
Just broke again with 48 people on. :(

Edit: I haz errors, hurray! http://pastebin.com/TaTzhBRY Also there are some folders in the user database. http://gyazo.com/a645eb93a39f95b458471eddf4b4e806

**Comment by geNAZt** [comment]
Do you get this warning: The AsyncEventBus has more than 3000 queued Events. ?

**Comment by geNAZt** [comment]
Can you update BungeeLib to this version: http://jenkins.cube-space.net/job/BungeeLib/2/artifact/target/Cubespace-BungeeLib.jar and tell me if it happens again ?

**Comment by IlPicasso** [comment]
It breaks constantly to me, that's the reason I have had to give access my staff to restart the bungee network at the moment this happens

**Comment by TagCraftMC** [comment]
I would have to wait until next crash to check for that error geNAZt (logs are too far gone), I will however update to that bungee when the chat breaks next or in the quite time (around 11 hours from now) and let you know.

Bungeelib*

**Comment by TagCraftMC** [comment]
Still getting the same PM errors atm with the new bungeelib, uptime is currently 6 hours. The crashes seem random so it could happen now or in 2 days time.

I ran a cc:report when the PM's were throwing errrors, hope it helps. http://pastebin.com/yz92ymYt

**Comment by TagCraftMC** [comment]
Died again about an hour ago whilst I was asleep. Look through the logs I found the following errors: http://pastebin.com/6UyMhusk

**Comment by geNAZt** [comment]
Should be fixed in the newest CloudChat

**Comment by TagCraftMC** [comment]
Requesting re-opening of this issue as it is not fixed.
Running latest version has still produced the same error, will start to look through logs again for any info.
On a side note can you fix the issue with console not able to run commands due to no permissions, this will allow me to run cc:report on once it breaks again.

**Comment by TagCraftMC** [comment]
Only Errors from update to CC: CloudChat version 8.1.2 are the PM ones, http://pastebin.com/27h2Fyd7

Re-cap on what this issue is.
At a random time for a random reason/error the bungee cloud chat plugin un-syncs with the bukkit cloudchat plugin. (The reason I believe it un-syncs is because you're still able to do and talk with the /fchat whilst on the factions server(It's still able to read the perms as /fchat is on bukkit level not bungee level))
When it un-syncs it causes no permissions to be read or sent from the bukkit cloudchat to the bungee one which in turn does not allow anyone to use the commands or read/send chat into any channels.
This happens across all the server and never effects a single server.
Having the permissions reload every x minutes does not help at all.

**Comment by geNAZt** [comment]
Can you try the newest build. It should fix the NPE you get

**Comment by TagCraftMC** [comment]
It has been 24 hours and it has not broken, I don't want to get my hopes up since it has lasted this long before :)

**Comment by TagCraftMC** [comment]
Broke again after a restart about 18 hours ago, I did a cc:report here is the outcome: http://pastebin.com/z4h4EnAZ

Now to go though hours of logs just as I wake up, fun ;)

Woo three errors: http://pastebin.com/XJrcS9qP

**Comment by TagCraftMC** [comment]
Chat system just died again after 10 hours up time -_- look in logs now.

I love cloudchat, but proxy restarts at just 10 hours up time in busy time sucks. Hope the logs help and thanks for the continued work.

Errors prior to dead chat: http://pastebin.com/Brat5fcT
CC:REPORT: http://pastebin.com/xrxzUgnh

Running
CC: 8.5.1
CCB: 3.3.0
YL-Bungee: 2.2.2
YL-Bukkit: 2.2.2
CCLIB: 2.0.2

**Comment by TagCraftMC** [comment]
Died again twice tonight in the past 4-5 hours, looking in logs again.
Might have to move away for CC soon, can't keep restarting in busy times, ruins peoples mini game matches ect.

Edit: 
Only one type of error: http://pastebin.com/cDhJ3ihx

Edit: Ill update to CCLIB 2.0.3 next time it dies and see if that helps.

**Comment by TagCraftMC** [comment]
Died three times again today.
We have updated to the latest everything cubespace wise.
We updated to the latest PEX as well.
We have tried with both the re-write UUID options off and on, both have the problem.
I still fell the issue somehow lies in either CCB or the LIB sending permissions to CC as it always seems cause CC to think you have no permissions.

Example of when the system is down (It's requested, but nothing is confirmed);

18.04.2014 09:54:16  [Logger/DEBUG] Getting PlayerDatabase for longtine2
18.04.2014 09:54:16  [Logger/DEBUG] Got new PluginMessage for Player longtine2: net.cubespace.PluginMessages.PermissionRequest@757caf64
18.04.2014 09:54:16  [Logger/DEBUG] Got new Affix Message for longtine2 - &8[&7Member&8]&7/
18.04.2014 09:54:16  [Logger/DEBUG] Getting PlayerDatabase for longtine2
18.04.2014 09:54:16  [Logger/DEBUG] Got new PluginMessage for Player longtine2: net.cubespace.PluginMessages.PermissionRequest@4cdf0a7e
18.04.2014 09:54:16  [Logger/DEBUG] Got new World Message for longtine2 - Factions_Spawn/Factions_Spawn

Example when system is restarted (Requested and confirmed);

18.04.2014 09:57:45  [Logger/DEBUG] Getting PlayerDatabase for Pariah
18.04.2014 09:57:45  [Logger/DEBUG] Got new PluginMessage for Player Pariah: net.cubespace.PluginMessages.PermissionRequest@16398462
18.04.2014 09:57:45  [Logger/DEBUG] Got new World Message for Pariah - TagCraftMC_Peace/TagCraftMC_Peace
18.04.2014 09:57:45  [Logger/DEBUG] Sending PluginMessage on 'CL-CloudChatPlug': net.cubespace.PluginMessages.PermissionRequest@16398462
18.04.2014 09:57:45  [Logger/DEBUG] Checking for Spam Rule violations
18.04.2014 09:57:46  [Logger/DEBUG] Firing Event: net.cubespace.lib.Permission.Event.PermissionChangedEvent
18.04.2014 09:57:46  [Logger/DEBUG] Calling Listener net.cubespace.CloudChat.Listener.PermissionChangedListener.onPermissionChanged
18.04.2014 09:57:46  [Logger/DEBUG] Getting Config for permissionContainers: net.cubespace.CloudChat.Config.PermissionContainers@6475b7d
18.04.2014 09:57:46  [Logger/DEBUG] Calling Listener net.cubespace.CloudChat.Module.ChannelManager.Listener.PermissionChangedListener.onPermissionChanged
18.04.2014 09:57:46  [Logger/DEBUG] Getting PlayerDatabase for Pariah

**Comment by geNAZt** [comment]
Do you get errors in Bukkit ?

**Comment by mcraftpete** [comment]
Hi, I am having an issue with the no permission after a restart is fine for a while then just perms drop at random time , I also seem to then have to /join global however I have resolved this part by adding perms into bungee configuration so default gas channel join perm , so basically we lose the perms on spigot but any bungee ones added are still working , if you could let me know that would b great. Thanks pete

**Comment by IlPicasso** [comment]
Chat died with 130 people on D:

**Comment by ravand1990** [comment]
same here chat dying after some uptime or after some server restarts, a bungee restart saves the issue

**Comment by TagCraftMC** [comment]
Currently at day 3 1/2 with chat stable, I don't want to restart bungee incase it goes to shit yet.
It seemed to go more stable once I deleted all the CC user files and set OverwriteUUIDs: false and AskForNewPermissionsEvery: 0, this however could just be a coincidence.

**Comment by mcraftpete** [comment]
tagcraft is this now working for you ? I still have the same problems , is like it loses all the persm after a random amount of time , never know when that could be , but its like all the perms break  ,I have the latest versions of everything cc8.5.1 cb 3.3.0 latest bunlib etc
let me kow if u manage to solve it , I really like the plugin so hopefully the bug can be resolved.

**Comment by TagCraftMC** [comment]
It was up for 4 days then died, it died when I was asleep so I was unable to check if it was caused by anything (Only keep 3-4 hour bungee logs as they spam a lot).
At the moment its' been 30-35 hours up time since the last time it died, it seems a lot more stable since changing those settings.
How ever I want to keep eye on it for the next week and see if the 4 day up time was just a fluke.

**Comment by mcraftpete** [comment]
I already done what you did above , reset all the data , and settings are same as yours overwrite uuids false and askforpermissions 0
Still the perms just drop from bukkit , always work directly after restarting bungee for x amount of time.
I haven't seen genazt reply to any of the threads fro a while either but hopefully he will be able to let us know soon if it us doing something wrong or if there is an issue.
I also have the problem that ppl don't always join global channel unless they actually type /join global , again works directly after bungee restart , I read somewhere that focus on join now does nothing as it is in bunlib so still wonmdering if bunlib is the overall issue here.

**Comment by johnfriedrich** [comment]
Did anyone find a solution for this?

**Comment by johnfriedrich** [comment]
try to set your open file limit to like 400.000 or so. I am just trying it. Hope it helps.
Just came to my mind. This COULD be the solution. Hopefully.

**Comment by mcraftpete** [comment]
no its not even worth the bother , its very outdated and hasn't been supported for over a year , I use mineversechat which is way better and more reliable CC breaks all the time its bad and not gonna get fixed. search the above on spigot , its supported and I have been using it for about 6 months without a single problem :)
