### ISSUE TITLE
Error spamming my console

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#81]
http://pastebin.com/ksYJYn7Q

**Comment by geNAZt** [comment]
Fixed in CloudChatBukkit 3.2.0

**Comment by IlPicasso** [comment]
I am still getting the entity damage error
http://pastebin.com/8X7Bjp0G

**Comment by geNAZt** [comment]
The problem is not complete. It just tells that there is a NPE but not where.
