### ISSUE TITLE
People dont join channel on login (permission problem?)

### ISSUE THREAD

**Issue by ravand1990** [geNAZt/CloudChat#89]
i seem to get alot of permissions errors from the log  with zPermissions with latest release build

Here my logs: http://puu.sh/81Jam.txt

Some people said i need to configure the joinorder.yml which i did but it didnt help

**Comment by geNAZt** [comment]
Have you tried to use the latest BungeeLib from Jenkins ? It should fix the permission exception. Have you banned or kicked or disconnected the player ?

**Comment by ravand1990** [comment]
Ok i will give it a try and tell u if it fixed it and no every user gets that error

**Comment by ravand1990** [comment]
Ok updated to bungeelib 2.0.2 and i still getting 
1. this: http://puu.sh/81NkD.txt
2. this: http://puu.sh/81NlP.txt

EDIT: AH you said jenkins.. gonna try 2.0.3 now

EDIT2: ok tested with 2.0.3 and getting this: http://puu.sh/81Ns3.txt

EDIT3: Ok i updated yamler too and it seems to work fine right now... just everyone joins the global chat even with joinOrder setup. Any ideas why?

**Comment by geNAZt** [comment]
hmmm that should not be. the permission system should have nothing todo with the channelmanager from Cloudchat

**Comment by geNAZt** [comment]
can you give me your joinOrder.yml ? and the channels for what you want to setup ?

**Comment by ravand1990** [comment]
http://puu.sh/81YDz.txt

and here an example of channels (all are the same just different names): http://puu.sh/81YF1.txt

**Comment by geNAZt** [comment]
Then its correct ?

**Comment by ravand1990** [comment]
No everyone joins Global chat

**Comment by geNAZt** [comment]
What server and what channel are you expecting to be in ?

**Comment by ravand1990** [comment]
for example on creative server i want them to be in the creative channel and also focused to the creative channel

**Comment by mcraftpete** [comment]
did u ever resolve this , I also tried join order etc and it would always join global chat even though my focus was set to hub in channel files and false on global channel yml.
